/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify-callback'
import { Route as IndexRouteImport } from './routes/index'

const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify-callback',
  path: '/spotify-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spotify-callback': typeof SpotifyCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/spotify-callback'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/spotify-callback'
  id: '__root__' | '/' | '/spotify-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spotify-callback': {
      id: '/spotify-callback'
      path: '/spotify-callback'
      fullPath: '/spotify-callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
